name: Trigger Netlify Build
on:
  schedule:
    - cron: '00 01,13 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.BUILD_HOOK}}
